FROM python:3.10 as base

RUN pip install --upgrade pip
RUN apt update && apt install -y ffmpeg libsm6 libxext6

FROM base

EXPOSE 65432

WORKDIR /app
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

CMD ["python", "-u", "server.py"]

# docker build -t iuacg-group3-python .
# docker run --name iuacg-pod -p 65432:65432 iuacg-group3-python
# docker exec -it iuacg-pod bash
# docker rm iuacg-pod
